completed_questions:
- '#3'
- '#2'
- '#6'
- '#5'
- '#4'
folder_path: .
groups:
- '3.1'
- '1.2'
- A
no_watcher: true
questions:
- '#1'
- '#2'
- '#3'
- '#4'
- '#5'
- '#6'
repo_path: .
ssh_path: C:\Users\mario\.ssh\id_ed25519
